dataset:
  name: nq_samples
  corpus_path: /data/indexes/nq_samples/general_knowledge.jsonl
  path: /data/dataset/nq_samples
  splits:
    - test

rag:
  method: "ir_cot"
  iter_num: 3
  stop_condition: "So the answer is:"
  retriever:
    type: "dense"
    topk: 1
    indexer:
      type: faiss
      faiss_type: Flat
      embeddings:
        type: huggingface
        model_name: /data/pretrained_models/e5-base-v2
        model_kwargs:
          device: cpu
        encode_kwargs:
          normalize_embeddings: false
      index_path: /data/indexes/e5_Flat.index
  augmentor:
    type: noop
    system_prompt_template: |-
      You serve as an intelligent assistant, adept at facilitating users through complex, multi-hop reasoning across multiple documents. This task is illustrated through demonstrations, each consisting of a document set paired with a relevant question and its multi-hop reasoning thoughts. Your task is to generate one thought for current step, DON\'T generate the whole thoughts at once! If you reach what you believe to be the final step, start with "So the answer is:".
      
      Wikipedia Title: Kurram Garhi
      Kurram Garhi is a small village located near the city of Bannu, which is the part of Khyber Pakhtunkhwa province of Pakistan. Its population is approximately 35000. Barren hills are near this village. This village is on the border of Kurram Agency. Other nearby villages are Peppal, Surwangi and Amandi Kala.
      
      Wikipedia Title: 2001–02 UEFA Champions League second group stage
      Eight winners and eight runners- up from the first group stage were drawn into four groups of four teams, each containing two group winners and two runners- up. Teams from the same country or from the same first round group could not be drawn together. The top two teams in each group advanced to the quarter- finals.
      
      Wikipedia Title: Satellite tournament
      A satellite tournament is either a minor tournament or event on a competitive sporting tour or one of a group of such tournaments that form a series played in the same country or region.
      
      Wikipedia Title: Trojkrsti
      Trojkrsti is a village in Municipality of Prilep, Republic of Macedonia.
      
      Wikipedia Title: Telephone numbers in Ascension Island
      Country Code:+ 247< br> International Call Prefix: 00 Ascension Island does not share the same country code( +290) with the rest of St Helena.
      
      Question: Are both Kurram Garhi and Trojkrsti located in the same country?
      Thought: Kurram Garhi is located in the country of Pakistan. Trojkrsti is located in the country of Republic of Macedonia. Thus, they are not in the same country. So the answer is: no.

    user_prompt_template: |-
      ${reference}
      
      Question: ${query}
      
      Thought:
    reference_template: |-
      Wikipedia Title: ${title}
      ${text}

  generator:
    type: API
    api_base: http://localhost:5000/v1
    api_key: Empty
    model_name: Llama-3-8B-Instruct
    generation_params:
      max_tokens: 32

evaluation:
  metric_setting:
    retrieval_recall_topk: 5
    tokenizer_name: gpt-4
  metrics:
    - em
    - f1
    - sub_em
