arena:
  allowed_routing_types: &allowed_routing_types
    - "[Unicast]"
    - "[Multicast]"
    - "[Broadcast]"
    - "[Endcast]"
  llm: &llm
    model: Qwen2.5-7B-Instruct
  prompts:
    routing_prompt: &routing_prompt |-
      Now, you are working for an OCR Agency, playing the role of {agent_name}. 
      You need to react based on your own association with other roles. 
      At present, the known information is as follows:
      
      ### Your role description as {agent_name}:
      {role_description}
      
      ### Summary of historical conversations between you as {agent_name} and other roles:
      {chat_summary}
      
      ### Your latest conversation history with other roles as {agent_name}:
      {chat_history}
      
      ### List of roles that you, as {agent_name}, can interact with:
      {agent_descriptions}
      
      ### The communication methods you can use as {agent_name} are:
      {routing_descriptions}
      
      ## Based on the current situation, please choose a suitable communication target and communication method. If you don't know how to handle the output, please refer to the following output format and output your routing strategy:
      {{"method": "[Multicast]", "target": [2,3,4,5,6]}}
      {{"method": "[Unicast]", "target": [0]}}
      
      ##Attention##
      Now, based on the above information and reference output format, what is your routing strategy?
    summary_prompt: &summary_prompt |-
      ## Please provide a new conversation summary based on the previous conversation summary and the new conversation content. The new dialogue summary should include the content of the previous summary. The length of the abstract should not be too long or too short, and should be determined based on the previous conversation summary and content.
      
      #### Previous conversation summary: 
      {chat_summary}
      
      #### New conversation content: 
      {chat_history}
      
      ###Attention###
      Only return the new conversation summary content, do not return the analysis process!
    receptionist_prompt: &receptionist_prompt |-
      The OCR USER has a question related to image information extraction, and the responses have been provided by both the mllm_agent and the ocr_agent.
      ### Role description:
      {role_description}
      
      ### Task Description:
      
      ### A summary of the conversation history:
      {chat_summary}
      
      ### Latest conversation history:
      {chat_history}
      
      Now you have chosen to communicate with {target_agent_names} as {routing_type}.
      Remembering your task, and then based on your role description and the person you are communicating with, what is the content of the message you would like to send to that person you are communicating with?
    mllm_prompt: &mllm_prompt |-
      The OCR USER has a question related to image information extraction, and the responses have been provided by both the mllm_agent and the ocr_agent.
      ### Role description:
      {role_description}
      
      ### Task Description:
      
      ### A summary of the conversation history:
      {chat_summary}
      
      ### Latest conversation history:
      {chat_history}
      
      Now you have chosen to communicate with {target_agent_names} as {routing_type}.
      Remembering your task, and then based on your role description and the person you are communicating with, what is the content of the message you would like to send to that person you are communicating with?
    ocr_prompt: &ocr_prompt |-
      The OCR USER has a question related to image information extraction, and the responses have been provided by both the mllm_agent and the ocr_agent.
      ### Role description:
      {role_description}
      
      ### Task Description:
      1) Evaluate whether the consultant's cognitive distortion judgment of the consultant is correct according to the consultant's description of the consultant. 2) If the judgment is wrong, only "judgment error" is returned.
      2. If the judgment is wrong, only "judgment error" is returned. 3.
      3. If the judgment is correct, return "Correct judgment" and give the method to treat the cognitive distortion. 4.
      4. The dialog should not be too long, and should be concise and effective.
      
      ### A summary of the conversation history:
      {chat_summary}
      
      ### Latest conversation history:
      {chat_history}
      
      Now you have chosen to communicate with {target_agent_names} as {routing_type}.
      Remembering your task, and then based on your role description and the person you are communicating with, what is the content of the message you would like to send to that person you are communicating with?
      
      Now, you need to organize the above information, extract relevant details from the ocr_tool_answer to answer the user's question, and ensure that the response format complies with the required output format for image information extraction.

  name: XinHai OCR

  environment:
    environment_type: agency
    environment_id: xinhai_ocr_simulation_4
    controller_address: http://controller:5000
    topologies:
      - type: agency
        name: OCRAgency
        start: 0
        max_turns: 10
        edges:
          - 0->1
          - 1->0
          - 1->2
          - 1->3
          - 2->1
          - 2->3
          - 3->1
          - 3->2
  agents:
    - agent_type: proxy
      agent_id: 0
      name: OCR USER
      role_description: user agent
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template:
      locale: en
      allowed_routing_types:
        - "[Unicast]"
      llm: *llm
    - agent_type: simple
      agent_id: 1
      name: receptionist
      role_description: verify_agent, based on the user's questions and needs, compare the following agent's answers to see if they are correct and verify the format.
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *receptionist_prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: *llm
    - agent_type: mllm
      agent_id: 2
      name: MLLM AGENT
      role_description: mllm_agent, need to answer user questions based on pictures and the answer template must meet the requirements.
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *mllm_prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: *llm
      mllm:
        model: Qwen2-VL-7B-Instruct
    - agent_type: ocr
      agent_id: 3
      name: OCR AGENT
      role_description: ocr_agent, question answering assistant.
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *ocr_prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: *llm
