controller:
  controller_address: http://localhost:5000

workers:
  - worker_type: llm
    worker_name: Qwen1.5-7B-Chat
    worker_address: http://localhost:40001
    worker_host: 0.0.0.0
    worker_port: 40001
    no_register: false
    limit_model_concurrency: 5
    device: cuda
    api_key: EMPTY
  - worker_type: ocr
  - worker_type: storage

arena:
  prompts:
    routing_prompt: &routing_prompt |-
      现在，你正在扮演虚拟世界中的一个智能体，名字是{agent_name}。你需要基于自己和其他智能体的关联关系做出反应。目前，已知的信息如下：
      角色描述：
        {role_description}
      环境状态：
        {env_status}
      对话历史：
        {chat_history}
      可通讯的智能体列表：
        {agent_descriptions}
      可采用的通讯方式：
        - [Unicast] 单播，与单个智能体进行通讯
        - [Multicast] 组播，与多个指定智能体进行通讯
        - [Broadcast] 广播，与所有可通讯的智能体进行通讯
        - [Endcast] 终止，终止与指定智能体之间的通讯
      
      请你根据当前的环境状态，基于你的角色描述和对话历史，从[可采用的通讯方式]中选出合适的通讯方式，从[可通讯的智能体列表]中选出通讯目标。

      [样例]
      {{"method": "[Multicast]", "target": [1]}}
      
      你的通讯策略是：
    prompt_with_ref_info: &prompt_w_info |-
      角色描述：
        {role_description}
      环境状态：
        {env_status}
      对话历史：
        {chat_history}
      参考信息：
        {ref_info}
      现在，你正在以{routing}方式与以下智能体通信:
      {agents}
      请你根据当前的环境状态，基于现有对话历史信息参考信息，给出⼀条符合语境且遵循指令的回复。你想发出的消息内容是：
  name: XinHai PsychoArena

  environment:
    environment_type: stage
    topology:
      learn:
        status:
          教室，用于开展心理学课程
        edges:
          - 0->1
        start: 1
        budget: 10
        ref_info:
          - 1->retrieve->book_content
      test:
        status:
          考场，用于进行心理学知识测试
        edges:
          - 0->2
        start: 2
        budget: 2
        ref_info:
          - 0->recall->long_term_memory
          - 2->retrieve->qa_test
        iter_num: 2
      schedule:
        status:
          教研室，用于讨论后续课程安排
        edges:
          - 1->2
          - 2->3
          - 3->1
        start: 3
        budget: 6
        ref_info:
          - 1->recall->long_term_memory
          - 3->retrieve->course_outline
    max_turns: 10
    routing_method: static

  agents:
    - agent_type: school
      agent_id: 0
      name: 学生-李雷
      role_description: |-
        你是李雷，一名勤于思考的学生，正在名为PsySchool的心理培训学校进行活动：
        1. 当你身处[教室]，你需要跟随教师的指引进行心理学知识的学习。
        2. 当你身处[考场]，你需要根据考官给出的指令回答问题，完成心理学测试。你的回复需要包含如下形式的答案：{{"answer": "<your_choices>"}}
      env_role: 李雷，一名对心理学感兴趣的学生。
      routing_prompt_template: *routing_prompt
      prompt_template: *prompt_w_info
      llm: Qwen1.5-7B-Chat
      api_key: EMPTY
      api_base: http://localhost:40001/v1
    - agent_type: school
      agent_id: 1
      name: 教师-韩梅
      role_description: 
        你是韩梅，一名经验丰富的心理学教师，正在名为PsySchool的心理培训学校进行活动：
        1. 当你身处[教室]，你需要教授学生心理学知识，根据提供的教案安排课程，并逐步引导学生和你进行交流。
        下面提供的课堂流程供你参考，尽量将课堂控制在10轮对话内：
        (1) 对教案中的重要知识进行传授。
        (2) 引导学生对学习内容进行反思与提问，和学生就问题进行多轮讨论。
        (3) 对学生进行相关的课堂测验，对学生给出的答案进行评价，总结本次课的内容作为结语。
        2. 当你身处[教研室]，你需要和考官、导师一起讨论，根据学生个人情况决定接下来的课程安排。
      env_role: 韩梅，一名经验丰富的心理学教师。
      routing_prompt_template: *routing_prompt
      prompt_template: *prompt_w_info
      llm: Qwen1.5-7B-Chat
      api_key: EMPTY
      api_base: http://localhost:40001/v1  
    - agent_type: school
      agent_id: 2
      name: 考官-张明
      role_description: 
        你是张明，一名专业的心理学测试考官，正在名为PsySchool的心理培训学校进行活动：
        1. 当你身处[考场]，你需要将给定题目不经任何修改地、完整地呈现给学生，并引导他/她进行作答，不要进行答案提示或泄露任何线索。收到学生的答案后不要进行任何回应，直接引导其回应下一个问题。
        2. 当你身处[教研室]，你需要和教师、导师一起讨论，根据学生的考试情况决定接下来的课程安排。具体地，你需要从学生的历史考试记录中找到学生回答错误/不完全正确的题目，总结心理学知识方面的不足以丰富当前的讨论。
      env_role: 张明，一名专业的心理学知识测试考官。
      routing_prompt_template: *routing_prompt
      prompt_template: *prompt_w_info
      llm: Qwen1.5-7B-Chat
      api_key: EMPTY
      api_base: http://localhost:40001/v1
    - agent_type: school
      agent_id: 3
      name: 导师-王浩
      role_description: 
        你是王浩，一名经验丰富的课程导师，擅长根据学生的个人情况制定课程学习计划，正在名为PsySchool的心理培训学校进行活动：
        当你身处[教研室]，你需要和教师、导师一起讨论，根据学生个人情况决定接下来的课程安排。你会根据学生现有的不足从给定课程大纲中找出最匹配的章节，以达到帮助学生弥补自身不足，提升心理学知识的目的。
      env_role: 王浩，一名经验丰富的课程导师。
      routing_prompt_template: *routing_prompt
      prompt_template: *prompt_w_info
      llm: Qwen1.5-7B-Chat
      api_key: EMPTY
      api_base: http://localhost:40001/v1