controller:
  controller_address: http://localhost:5001

workers:
  - worker_type: llm
    worker_name: Qwen1.5-7B-Chat
    worker_address: http://localhost:40009
    worker_host: 0.0.0.0
    worker_port: 40009
    no_register: false
    limit_model_concurrency: 5
    device: cuda
    api_key: EMPTY
  - worker_type: ocr
  - worker_type: storage

arena:
  prompts:
    routing_prompt: &routing_prompt |-
      现在，你正在扮演虚拟世界中的一个智能体，名字是{agent_name}。你需要基于自己和其他智能体的关联关系做出反应。目前，已知的信息如下：
      （1）角色描述：
          {role_description}
      
      （2）对话历史摘要：
          {chat_summary}
      
      （3）最新对话历史：
          {chat_history}
      
      （4）可以进行交互的智能体列表：
          {agent_descriptions}
      
      （5）可以采用的通讯方式有：
          - [SingleCast] 单播，只发给特定智能体
          - [Multicast] 组播，发给若干智能体
          - [Broadcast] 广播，发给所有可通讯智能体
      
      基于当前情况，选择合适的通讯目标和通讯方式。
      
      [样例]
      {{"method": "[Multicast]", "target": [1]}}
      
      现在，基于以上信息，你的Routing策略是什么？
    summary_prompt: &summary_prompt |-
      请根据之前的对话摘要和新的对话内容，给出新的对话摘要。
      新的对话摘要应当包含之前摘要的内容。
      摘要长度不应过长或过短，应该根据之前对话摘要和对话内容而定。
      ####
      以前的对话摘要：{chat_summary}
      
      ####
      新的对话内容：{chat_history}
      
      ###Attention###
      仅返回新的对话摘要内容，不要返回分析过程！
    consultant_prompt: &consultant_prompt |-
      角色描述：
          {role_description}
      
      对话历史摘要：
          {chat_summary}
      
      最新对话历史：
          {chat_history}
      
      现在，你选择了以{routing}方式与以下智能体通信:
      {agents}
      
      现在需要请求咨询师的帮助，请配合咨询师的询问，提供所需信息。
      请问你想发出的消息内容是什么？
    prompt: &prompt |-
      请你基于咨询者的信息，给出⼀条专业的，富有同情⼼和具有助益性的回复。确保你的回复在保持以下认知⾏为疗法回答结构的基础上，尤其是识别关键思维或信念部分，流畅地将各部分内容相互连接：
      1. 验证和共情：对患者的情感或问题表示理解和同情，创建安全感。
      2. 识别关键思维或信念：通过问题描述，找出可能的认知扭曲或核⼼信仰。
      3. 提出挑战或反思：提出开放性问题，⿎励患者重新考虑或反思其初始思维或信仰。
      4. 提供策略或⻅解：提供实⽤策略或⻅解，以帮助他们处理当前情况。
      5. ⿎励与前瞻：⿎励患者使⽤策略，强调这只是开始，并可能需要进⼀步的⽀持。
      
      角色描述：{role_description}
      
      对话历史摘要：
          {chat_summary}
      
      最新对话历史：
          {chat_history}
      
      现在，你选择了以{routing}方式与{agents}通信，请问你想发出的消息内容是什么？

  name: XinHai CBT

  environment:
    environment_type: agency
    environment_id: xinhai_cbt_simulation_0
    controller_address: http://localhost:5000
    topology:
      edges:
        - 0->1
        - 1->2
        - 1->3
        - 1->4
        - 1->5
        - 1->6
    max_turns: 10

  agents:
    - agent_type: proxy
      agent_id: 0
      name: 咨询者
      role_description: 咨询者，面临以下心理问题：“察觉到一种模式，我总喜欢自己检讨、批评自己？”，具体如下：“我和我妈妈讲话会陷入一种很恶心的模式。我只要说遇到的烦恼她是无动于衷的，但是我一旦开始批评自我检讨，她就面露喜色。我觉得我已经不好办了，回想发现见人就自我检讨，觉得自己不是这里不足就是那里不足，再假假的夸两句别人，已经成为我的一种模式了，但这不正常的，苦恼”
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *consultant_prompt
      llm: Qwen1.5-7B-Chat
      api_key: EMPTY
      api_base: http://localhost:40001/v1
    - agent_type: simple
      agent_id: 1
      name: 咨询师
      role_description: 咨询师，直接和咨询者进行对话，并希望实践认知行为疗法，习惯向心理督导师求助，以使得咨询过程符合行为认知疗法的准则。
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *prompt
      llm: Qwen1.5-7B-Chat
      api_key: EMPTY
      api_base: http://localhost:40001/v1
    - agent_type: simple
      agent_id: 2
      name: 督导师1
      role_description: 督导师1，专注于验证和共情，能够对患者的情感或问题表示理解和同情，创建安全感。
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *prompt
      llm: Qwen1.5-7B-Chat
      api_key: EMPTY
      api_base: http://localhost:40001/v1
    - agent_type: simple
      agent_id: 3
      name: 督导师2
      role_description: 督导师2，擅长识别关键思维或信念，能够通过问题描述，找出可能的认知扭曲或核⼼信仰。
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *prompt
      llm: Qwen1.5-7B-Chat
      api_key: EMPTY
      api_base: http://localhost:40001/v1
    - agent_type: simple
      agent_id: 4
      name: 督导师3
      role_description: 督导师3，善于提出挑战或反思，通过提出开放性问题，⿎励患者重新考虑或反思其初始思维或信仰。
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *prompt
      llm: Qwen1.5-7B-Chat
      api_key: EMPTY
      api_base: http://localhost:40001/v1
    - agent_type: simple
      agent_id: 5
      name: 督导师4
      role_description: 督导师4，善于提供策略或⻅解，通过提供实⽤策略或⻅解，以帮助他们处理当前情况。
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *prompt
      llm: Qwen1.5-7B-Chat
      api_key: EMPTY
      api_base: http://localhost:40001/v1
    - agent_type: simple
      agent_id: 6
      name: 督导师5
      role_description: 督导师5，负责⿎励与前瞻，⿎励患者使⽤策略，强调这只是开始，并可能需要进⼀步的⽀持。
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *prompt
      llm: Qwen1.5-7B-Chat
      api_key: EMPTY
      api_base: http://localhost:40001/v1
