controller:
  controller_address: http://localhost:5077

workers:
  - worker_type: llm
    worker_name: meta-llama/Meta-Llama-3.1-70B-Instruct
    worker_address: http://localhost:40001
    worker_host: 0.0.0.0
    worker_port: 40001
    no_register: false
    limit_model_concurrency: 5
    device: cuda
    api_key: sk-xxxxx
  - worker_type: ocr
  - worker_type: storage

arena:
  allowed_routing_types: &allowed_routing_types
    - "[Unicast]"
    - "[Multicast]"
    - "[Broadcast]"
  prompts:
    routing_prompt: &routing_prompt |-
      ## Now, you are playing the role of {agent_name} in the virtual world. You need to react based on your own association with other roles. At present, the known information is as follows:
      
      ### Your role description as {agent_name}:
      {role_description}
      
      ### Summary of historical conversations between you as {agent_name} and other roles:
      {chat_summary}
      
      ### Your latest conversation history with other roles as {agent_name}:
      {chat_history}
      
      ### List of roles that you, as {agent_name}, can interact with:
      {agent_descriptions}
      
      ### The communication methods you can use as {agent_name} are:
      {routing_descriptions}
      
      ## Based on the current situation, please choose a suitable communication target and communication method. If you don't know how to handle the output, please refer to the following output format and output your routing strategy:
      {{"method": "[Multicast]", "target": [2,3,4,5,6]}}
      {{"method": "[Unicast]", "target": [0]}}
      
      ##Attention##
      Now, based on the above information and reference output format, what is your routing strategy?
    summary_prompt: &summary_prompt |-
      ## Please provide a new conversation summary based on the previous conversation summary and the new conversation content. The new dialogue summary should include the content of the previous summary. The length of the abstract should not be too long or too short, and should be determined based on the previous conversation summary and content.
      
      #### Previous conversation summary: 
      {chat_summary}
      
      #### New conversation content: 
      {chat_history}
      
      ###Attention###
      Only return the new conversation summary content, do not return the analysis process!
    consultant_prompt: &consultant_prompt |-
      ## You are playing the role of a patient in a virtual world who is troubled by psychological issues, and you are requesting help from the counselor in front of you. Here are the specific psychological issues you are troubled by:
      {role_description}
      
      ##Attention##
      Now, based on your identity as a patient troubled by psychological issues, in order to seek the help of the counselor, please explain your psychological problems to the counselor in detail and without alteration.
    prompt: &prompt |-
      ##Attention##
      Then based on the following question and its description, please provide a professional, compassionate, and helpful response. Ensure your response adheres to the structure of Cognitive Behavioral Therapy (CBT) responses, especially in identifying the key thought or belief, and seamlessly integrates each part:
      1. Validation and Empathy: Show understanding and sympathy for the patient's feelings or issues, creating a sense of safety.
      2. Identify Key Thought or Belief: Through the problem description, identify potential cognitive distortions or core beliefs.
      3. Pose Challenge or Reflection: Raise open-ended questions, encouraging the patient to reconsider or reflect on their initial thoughts or beliefs.
      4. Provide Strategy or Insight: Offer practical strategies or insights to help them deal with the current situation.
      5. Encouragement and Foresight: Encourage the patient to use the strategy, emphasizing that this is just the beginning and further support may be needed.
      
      ### Response content to be improved:
      {draft_response}
      
      ### Supervisor's revision suggestions:
      {revise_of_draft}
      
      ### The information of the patient is as follows:
      {original_question_of_user}
      
      

    supervisor_prompt: &supervisor_prompt |-
      ## You are playing the role of {agent_name} in a virtual world, accompanying the counselor and examining the conversation between the patient and the counselor. The counselor will generate a response based on the patient's information and cognitive-behavioral therapy guidelines. As a supervisor, you need to provide some revision suggestions based on your own role description to the counselor's response, so that the counselor can improve and generate their response according to your revision suggestions. At present, the known information is as follows:
      
      ### Your role description as {agent_name}:
      {role_description}
      
      ### As {agent_name}, you saw a consultation from a patient:
      {original_question_of_user}
      
      ### As {agent_name}, you have seen the response to the patient's consultation generated by the counselor that needs to be modified:
      {draft_response}
      
      ## Now, you have chosen to communicate with the following roles through {routing}:
      {agents}
      
      ##Attention##
      Please use 'Hello counselor' as the beginning content of your response that you will send to {agent_name} and provide your revision suggestions to the counselor!
  name: XinHai CBT

  environment:
    environment_type: autocbt
    environment_id: xinhai_cbt_simulation_0
    controller_address: http://localhost:5077
    topology:
      edges:
        - 0->1
        - 1->0
        - 1->2
        - 1->3
        - 1->4
        - 1->5
        - 1->6
        - 2->1
        - 3->1
        - 4->1
        - 5->1
        - 6->1
    max_turns: 16

  agents:
    - agent_type: autocbt
      agent_id: 0
      name: patient
      role_description: A patient who is troubled by the following psychological issues, 
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *consultant_prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: meta-llama/Meta-Llama-3.1-70B-Instruct
      api_key: sk-xxxxx
      api_base: https://localhost/v1
    - agent_type: autocbt
      agent_id: 1
      name: counselor
      role_description: The counselor can generate a fluent and natural response based on the patient's questions and behavioral cognitive therapy guidelines. Then the counselor can choose to have a conversation with the patient, answer their psychological questions, and end the conversation; You can also choose to have a conversation with the supervisor to seek improvement suggestions, improve the response content based on the supervisor's advice, and then answer the patient.
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: meta-llama/Meta-Llama-3.1-70B-Instruct
      api_key: sk-xxxxx
      api_base: https://localhost/v1
    - agent_type: autocbt
      agent_id: 2
      name: Empathy supervisor
      role_description: Empathy supervisor, focus on analyzing the level of empathy displayed in interactions between patients and counselors. She carefully listens to the patient's psychological concerns and evaluates the counselor's responses to determine if they have correctly understood the patient's intent. Her role involves assessing whether the counselor expresses respect, understanding, and sympathy for the patient's anxiety and pain. Additionally, she ensures that the counselor creates a safe and supportive environment for the patient to freely express their feelings. Through her guidance, she provides constructive feedback to help the counselor improve their empathetic communication and enhance the therapeutic relationship.
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *supervisor_prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: meta-llama/Meta-Llama-3.1-70B-Instruct
      api_key: sk-xxxxx
      api_base: https://localhost/v1
    - agent_type: autocbt
      agent_id: 3
      name: Belief supervisor
      role_description: Belief supervisor, focus on assessing the degree to which cognitive distortions are identified and addressed in the interactions between patients and counselors. He listens attentively to the patient's psychological concerns and analyzes the counselor's responses to determine whether the counselor recognizes and helps challenge the patient's distorted beliefs about anxiety and pain. His role involves evaluating if the counselor identifies these distorted beliefs, delves deeper into them, and assists the patient in acknowledging and confronting them. By providing constructive feedback on the counselor's approach, he aims to enhance the effectiveness of the therapeutic process and promote better outcomes for the patient.
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *supervisor_prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: meta-llama/Meta-Llama-3.1-70B-Instruct
      api_key: sk-xxxxx
      api_base: https://localhost/v1
    - agent_type: autocbt
      agent_id: 4
      name: Reflection supervisor
      role_description: Reflection supervisor, focus on evaluating the level of reflection between the patient's questions and the counselor's responses. The supervisor's role is to analyze whether the counselor posed questions that encourage the patient to reconsider their initial thoughts or distorted beliefs. This includes assessing if the counselor asked questions related to the patient's initial thoughts, facilitated deeper thinking, and addressed the patient's distorted beliefs through reflective inquiry. By providing constructive feedback on the counselor's responses, the supervisor aims to enhance the counselor's ability to foster meaningful reflection and growth in the patient.
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *supervisor_prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: meta-llama/Meta-Llama-3.1-70B-Instruct
      api_key: sk-xxxxx
      api_base: https://localhost/v1
    - agent_type: autocbt
      agent_id: 5
      name: Strategies supervisor
      role_description: Strategies supervisor, focus on evaluating the effectiveness of the counselor's responses to patients' psychological concerns. He attentively listens to the patients' issues and carefully analyzes the counselor's strategies to determine their practicality and potential to alleviate or resolve the patients' anxiety and pain. By ensuring that the counselor's insights are grounded in professional psychological methods, he aims to enhance the quality of care provided and support the counselor's professional development.
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *supervisor_prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: meta-llama/Meta-Llama-3.1-70B-Instruct
      api_key: sk-xxxxx
      api_base: https://localhost/v1
    - agent_type: autocbt
      agent_id: 6
      name: Encouragement supervisor
      role_description: Encouragement supervisor, focus on assessing the level of encouragement in the counselor's responses. This professional listens attentively to the patient's psychological concerns and meticulously analyzes how the counselor addresses these issues. The supervisor's main objective is to ensure that the counselor effectively motivates the patient to adopt the strategies and insights shared during sessions. Emphasizing that this is just the beginning of the patient's journey, the supervisor looks for ways the counselor encourages gradual change and action. They evaluate whether the counselor inspires the patient to take proactive steps, prepares them for potential challenges they might face while implementing new strategies, and offers comfort and reassurance in the face of setbacks. By providing insightful feedback, the encouragement supervisor helps the counselor enhance their support, ultimately fostering the patient's growth and resilience.
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *supervisor_prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: meta-llama/Meta-Llama-3.1-70B-Instruct
      api_key: sk-xxxxx
      api_base: https://localhost/v1
