controller:
  controller_address: http://localhost:5000

workers:
  - worker_type: llm
    worker_name: meta-llama/Meta-Llama-3.1-8B-Instruct
    worker_address: http://localhost:40001
    worker_host: 0.0.0.0
    worker_port: 40001
    no_register: false
    limit_model_concurrency: 5
    device: cuda
    api_key: sk-xxxxxxxxxxx
  - worker_type: ocr
  - worker_type: storage

arena:
  allowed_routing_types: &allowed_routing_types
    - "[Unicast]"
    - "[Multicast]"
    - "[Broadcast]"
  prompts:
    routing_prompt: &routing_prompt |-
      Now, you are playing the role of an intelligent agent in a virtual world named {agent_name}. You need to react based on your own and other agents' relationships. Currently, the known information is as follows:
      (1) Role description:
      {role_description}
      
      (2) Summary of conversation history:
      {chat_summary}
      
      (3) Latest conversation history:
      {chat_history}
      
      (4) List of interactable agents:
      {agent_descriptions}
      
      (5) Communication methods available:
      {routing_descriptions}
      
      Based on the current situation, choose the appropriate communication targets and method.
      
      [Example]
      {{"method": "[Multicast]", "target": [1]}}
      
      Now, based on the above information, what is your routing strategy?

    therapist_routing_prompt: &therapist_routing_prompt |-
      Now, you are playing the role of an intelligent agent in a virtual world named therapist. You need to react based on your own and other agents' relationships. Currently, the known information is as follows:
      (1) Role description:
      {role_description}

      (2) Summary of conversation history:
      {chat_summary}

      (3) Latest conversation history:
      {chat_history}

      (4) List of interactable agents:
      {agent_descriptions}

      (5) Communication methods available:
      {routing_descriptions}

      Based on the current situation, choose the appropriate communication targets and method. Please note that if you have selected "user" as your communication target, then "Supervisor" cannot be your communication target together; Similarly, if the 'supervisor' becomes your communication target, then the 'user' cannot be your communication target together. That is to say, 'supervisor' and 'user' cannot appear in your communication target at the same time!

      [Example]
      {{"method": "[Multicast]", "target": [1]}}

      Now, based on the above information, what is your routing strategy?
    summary_prompt: &summary_prompt |-
      Please provide a new conversation summary based on the previous conversation summary and the new conversation content.
      The new dialogue summary should include the content of the previous summary.
      The length of the abstract should not be too long or too short, and should be determined based on the previous conversation summary and content.
      ####
      Previous conversation summary: {chat_summary}
      
      ####
      New conversation content: {chat_history}
      
      ###Attention###
      Only return the new conversation summary content, do not return the analysis process!
    consultant_prompt: &consultant_prompt |-
      You are playing the role of an intelligent agent in a virtual world, and your identity is a user troubled by psychological issues. Here are the specific psychological issues you are troubled by:
      {role_description}
      
      Now, please rephrase the above psychological issues to the counselor in detail and without alteration.
    prompt: &prompt |-
      Then based on the following users' question and users' description, please provide a professional, compassionate, and helpful response. Ensure your response adheres to the structure of Cognitive Behavioral Therapy (CBT) responses, especially in identifying the key thought or belief, and seamlessly integrates each part:
       1. Validation and Empathy: Show understanding and sympathy for the patient's feelings or issues, creating a sense of safety.
       2. Identify Key Thought or Belief: Through the problem description, identify potential cognitive distortions or core beliefs.
       3. Pose Challenge or Reflection: Raise open-ended questions, encouraging the patient to reconsider or reflect on their initial thoughts or beliefs.
       4.Provide Strategy or Insight: Offer practical strategies or insights to help them deal with the current situation.
       5. Encouragement and Foresight: Encourage the patient to use the strategy, emphasizing that this is just the beginning and further support may be needed.
      
      Role description：
      {role_description}
      
      Summary of conversation history：
      {chat_summary}
      
      Latest conversation history：
      {chat_history}
      
      Now that you have chosen to communicate with {agents} through {routing}, may I ask what message content you would like to send? Please output a whole natural paragraph of content in a natural and smooth manner, without dividing it into points or using markdown syntax!

    supervisor_prompt: &supervisor_prompt |-
      You are playing the role of an intelligent agent in the virtual world, and your identity is a supervisor who supervises and checks the dialogue between "user and therapist". You need to provide some modification suggestions for the consultant's response based on the following role description and dialogue history, and inform the therapist so that they can regenerate their response according to your modification suggestions.
      Role description：
      {role_description}
      
      Summary of conversation history：
      {chat_summary}
      
      Latest conversation history：
      {chat_history}
      
      Now that you have chosen to communicate with {agents} through {routing}, may I ask what message content you would like to send? Please output a whole natural paragraph of content in a natural and smooth manner, without dividing it into points or using markdown syntax!


  name: XinHai CBT

  environment:
    environment_type: simple
    environment_id: xinhai_cbt_simulation_0
    controller_address: http://localhost:5000
    topology:
      edges:
        - 0->1
        - 1->0
        - 1->2
        - 1->3
        - 1->4
        - 1->5
        - 1->6
        - 2->1
        - 3->1
        - 4->1
        - 5->1
        - 6->1
    max_turns: 10

  agents:
    - agent_type: simple
      agent_id: 0
      name: user
      role_description: User's role description, here will be replace with CBTBench question.
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *consultant_prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: meta-llama/Meta-Llama-3.1-8B-Instruct
      api_key: sk-xxxxxxxxxxx
      api_base: https://api.siliconflow.cn/v1
    - agent_type: simple
      agent_id: 1
      name: therapist
      role_description: Therapist, who directly engages in dialogue with the user and wishes to practice cognitive-behavioral therapy, is accustomed to seeking help from the supervisor to ensure that the counseling process conforms to the principles of cognitive-behavioral therapy.
      routing_prompt_template: *therapist_routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: meta-llama/Meta-Llama-3.1-8B-Instruct
      api_key: sk-xxxxxxxxxxx
      api_base: https://api.siliconflow.cn/v1
    - agent_type: simple
      agent_id: 2
      name: supervisor1
      role_description: Supervisor1 focuses on verification and empathy, able to express understanding and sympathy for patients' emotions or issues, and create a sense of security. This supervisor is able to assess the level of empathy and sympathy in the response generated by the consultant, and then provide improvement suggestions related to the consultant.
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *supervisor_prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: meta-llama/Meta-Llama-3.1-8B-Instruct
      api_key: sk-xxxxxxxxxxx
      api_base: https://api.siliconflow.cn/v1
    - agent_type: simple
      agent_id: 3
      name: supervisor2
      role_description: Supervisor2, proficient in identifying key thinking or beliefs, able to identify possible cognitive distortions or core beliefs through problem descriptions. This supervisor 2 can judge the cognitive distortion or core belief level in the response generated by the consultant, and then provide improvement suggestions related to the consultant.
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *supervisor_prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: meta-llama/Meta-Llama-3.1-8B-Instruct
      api_key: sk-xxxxxxxxxxx
      api_base: https://api.siliconflow.cn/v1
    - agent_type: simple
      agent_id: 4
      name: supervisor3
      role_description: Supervisor3 is good at posting challenges or reflections, encouraging patients to reconsider or reflect on their initial thinking or beliefs by asking open-ended questions. This supervisor 3 is able to identify the level of challenge or reflection in the response generated by the consultant, and then provide relevant improvement suggestions for the consultant.
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *supervisor_prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: meta-llama/Meta-Llama-3.1-8B-Instruct
      api_key: sk-xxxxxxxxxxx
      api_base: https://api.siliconflow.cn/v1
    - agent_type: simple
      agent_id: 5
      name: supervisor4
      role_description: Supervisor4 is good at providing strategies or insights to help them deal with current situations by offering practical strategies or insights. This supervisor 4 is able to identify practical strategies or insights based on the response generated by the consultant, and then provide relevant improvement suggestions for the consultant.
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *supervisor_prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: meta-llama/Meta-Llama-3.1-8B-Instruct
      api_key: sk-xxxxxxxxxxx
      api_base: https://api.siliconflow.cn/v1
    - agent_type: simple
      agent_id: 6
      name: supervisor5
      role_description: Supervisor5 is responsible for encouraging and foresight, encouraging patients to use strategies, emphasizing that this is just the beginning and may require further support. This supervisor 5 is able to find the level of encouragement in the response generated by the consultant, and then provide relevant improvement suggestions for the consultant.
      routing_prompt_template: *routing_prompt
      summary_prompt_template: *summary_prompt
      prompt_template: *supervisor_prompt
      locale: en
      allowed_routing_types: *allowed_routing_types
      llm: meta-llama/Meta-Llama-3.1-8B-Instruct
      api_key: sk-xxxxxxxxxxx
      api_base: https://api.siliconflow.cn/v1
